#shaders/shaders.properties

#Minecraft Settings
oldLighting=false
underwaterOverlay = false
stars=true
vignette=false
dynamicHandLight=true
moon=true
separateAo=false
clouds=false

#ifdef PREETHAM_SKY
sun=false
#else
sun=true
#endif

particles.before.deferred=true
rain.depth=true
beacon.beam.depth=true

program.composite1.enabled=FOG
program.deferred1.enabled=FOG

program.composite2.enabled=BLOOM
program.composite3.enabled=BLOOM
program.composite4.enabled=BLOOM

scale.composite2=0.5
scale.composite3=0.5

scale.deferred1=0.5

# aka gaux4
texture.gbuffers.colortex7=textures/noise.png
texture.composite.colortex7=textures/noise.png
